### ISSUE TITLE
NobleCoin does not generate valid blocks

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/powerpool#121]
Hi, 

I've not had any success with getting noblecoin to generate valid blocks. I've tried with and without tx_messages enabled but still ends as an orphan.

Has anyone else see this issue and was able to rectify it?

My PP config:

NOBLE:
    poll: False
    type: powerpool.jobmanagers.MonitorNetwork
    algo: scrypt
    currency: NOBL
    tx_messages: true
    pool_address: 9fXsWhZRvjM6exxNZEeYN75dEf78ezjfuC
    coinservs:
        - port: *****
          address: 127.0.0.1
          username: noblecoinrpc
          password: **********
          poll_priority: 100

Cheers!

**Comment by ericecook** [comment]
NOBL is a PoS hybrid coin. PoS, hybrids, and TX messages are not currently supported.

This issue tracker is only for mainline powerpool topics, so I'll close this, but if you wish to reach out to others who may be able to help I'd recommend shooting a message out to the developer mailing list (https://groups.google.com/forum/#!forum/simplecrypto-dev)

**Comment by crackfoo** [comment]
Oh really?? I didn't know it was, thought it was straight up pow.

sorry.
