### ISSUE TITLE
Darkcoin orphans

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/powerpool#123]
Hi,

Not sure what the problem is or if there is an update that needs to happen because of recent upgrades to darkcoind, but I'm getting quite a few orphans now as it seems pp doen't always pull the proper block value??

http://www.xpool.ca/blocks/DRK

Anyone else seeing this?

**Comment by ericecook** [comment]
Sorry it took so long, PR is merged in now. Made a few minor tweaks which still need some testing tho
