### ISSUE TITLE
what is that any help ?

### ISSUE THREAD

**Issue by napoleon2121** [simplecrypto/powerpool#126]
```
Traceback (most recent call last):
  File "/usr/local/bin/pp", line 9, in <module>
    load_entry_point('powerpool==0.6.3', 'console_scripts', 'pp')()
  File "/root/powerpool/powerpool/main.py", line 44, in main
    PowerPool.from_raw_config(raw_config, vars(args)).start()
  File "/root/powerpool/powerpool/main.py", line 94, in from_raw_config
    obj = typ(config)
  File "/root/powerpool/powerpool/stratum_server.py", line 78, in __init__
    self._configure(config)
  File "/root/powerpool/powerpool/lib.py", line 164, in _configure
    "component {}".format(key, self.__class__.__name__))
powerpool.exceptions.ConfigurationError: Key algo is a required configuration value for component StratumServer
```

**Comment by microlost** [comment]
I also met the same problem

**Comment by napoleon2121** [comment]
PP:
    type: powerpool.main.PowerPool
    procname: powerpool
    term_timeout: 10
    extranonce_serv_size: 4
    extranonce_size: 4
    algorithms:
          scrypt:
              module: ltc_scrypt.getPoWHash
              hashes_per_share: 65536
    server_number: 0

redis_scrypt:
    type: powerpool.reporters.RedisReporter
    pool_report_configs:
        - worker_format_string: "{chain}"
          user: "pool"
        - worker_format_string: "{currency}"
          user: "pool_currency"
          report_merge: False
    attrs:
        chain: LTC
    redis:
        port: 6379
    chain: 1
LTC:
    type: powerpool.jobmanagers.MonitorNetwork
    algo: scrypt
    currency: LTC
    pool_address: LYExXWEPs5oWjScR1fYzwSuo8DcQWNcHpF
    coinservs:
          port: 20001
          address: 127.0.0.1
          username: admin1
          password: 123
          poll_priority: 200
          port: 20002
          address: 127.0.0.1
          username: admin1
          password: 123
          poll_priority: 100
scrypt_STRAT:
    type: powerpool.stratum_server.StratumServer
    algo: scrypt
    jobmanager: LTC
    reporter: redis_scrypt
    start_difficulty: 64
    port: 3334
    vardiff:
      enabled: True
      spm_target: 30
      interval: 10
      tiers:
          - 8
          - 16
          - 32
          - 64
         - 96
          - 128
          - 192
          - 256
          - 512
          - 1024
          - 2048
          - 4096
          - 8192
MON:
     type: powerpool.monitor.ServerMonitor

**Comment by ericecook** [comment]
These aren't bugs, they are configuration errors. Configuration questions are best asked on the mailing list (https://groups.google.com/forum/#!forum/simplecrypto-dev)

@napoleon2121 The exception you've listed is indicating that you have a Stratum Server component which doesn't have an 'algo' key defined. 

The config file you've posted has several errors.
 - Spacing in YAML is important - and the spacing in your Stratum server's vardiff tiers is messed up
 - Hypens denote a list item. Your coinservers should each be a list item, refer to the example (https://github.com/simplecrypto/powerpool/blob/master/config.example.yml#L358) if you're unsure.

After fixing those things I got your config file running - so it should be good
