### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by TheCashier** [simplecrypto/powerpool#132]
Hi, is it possible to add Skein and Qubit Algorithm to powerpool ?

**Comment by icook** [comment]
Algorithms can be dynamically defined by overriding config values here:

https://github.com/simplecrypto/powerpool/blob/master/powerpool/main.py#L68

Also explained in more depth here:

https://github.com/simplecrypto/powerpool/blob/master/config.example.yml#L55

**Comment by TheCashier** [comment]
I will have a look and try, thanks

**Comment by TheCashier** [comment]
I understand how you add the module in config but do you have any tips on how do i have to install Skein and Qubit algos and how to configure them, i m not used to this, some help would be nice

**Comment by icook** [comment]
I would look at the `stratum-mining` version and see which python module they use. You need to install a new module and configure it. The `module` config portion will be a full path to the python function that performs the hashing operation.

Hope that helps a bit, I know it's not super clear, sorry.
