### ISSUE TITLE
Lyra2RE support for pp?

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/powerpool#133]
I'm wondering if the standard pp supports Lyra2RE? I see there are configs for it in scm:

[algos.lyra2re]
hashes_per_share = 33554432
#450kh/s $85 5.294117647khs/$
normalize_mult = 6.044444462
display = "Lyra2RE"

What all is needed to have this support and are the scm configs valid?

Thanks

**Comment by icook** [comment]
I believe the SCM configs are valid. I just replied to your email, but for those looking I'll copy:

>I'm assuming you want to support VTC, which actually needs Lyre2RE2 now. Use "pip install git+https://github.com/metalicjames/lyra2re-hash-python" and add the algorithm config as described in documentation here: https://github.com/simplecrypto/powerpool/blob/master/config.example.yml#L57

This stuff is better asked on the mailing list FYI. I know we're not the best about replying promptly on there, I'll try to get better about it.
