### ISSUE TITLE
how to add pool at runtime?

### ISSUE THREAD

**Issue by frndxyz** [simplecrypto/powerpool#134]

**Comment by icook** [comment]
I don't understand, you need to explain your question. Also, please try to keep questions to the mailing list.

**Comment by frndxyz** [comment]
@icook  , i want add new mining pool at runtime in simplecoin..

**Comment by ericecook** [comment]
@frndxyz, If I understand correctly, you're asking if it is possible to update SCM while it is running to include information about a PowerPool instance. it is not currently possible to do that, although it is something that may be added eventually. For now, you'll have to change the SCM configuration and restart it.
