### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by icook** [simplecrypto/powerpool#93]
Long, high load instances are eating more and more RAM as they run, as much as 4GB after several weeks at a few gigahash. This is possibly caused by:

1. Jobs not getting properly GCed. Likely a reference loop that Python cannot break.
2. Long connected peers keeping huge job mapping lists. Less likely.

**Comment by icook** [comment]
@ericecook Is this still occuring? I don't believe we've had issues with this anymore.

**Comment by ericecook** [comment]
@icook I'm unsure. We haven't had memory issues since moving the scheduler out to cron jobs

**Comment by icook** [comment]
Ah, right. That should probably be documented in simplecoin_multi now that I think about it...

I'll go ahead and close this since it seems to be resolved by #98.
